import type { Config } from 'tailwindcss';

// Design tokens ported verbatim from the Aetheris Protocol brief's
// tailwind.config so the rendered UI matches the approved mock exactly.
const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#191c1f',
        'on-tertiary-container': '#7d5800',
        'secondary-fixed-dim': '#ebb2ff',
        'error-container': '#93000a',
        outline: '#849495',
        'surface-container-high': '#282a2e',
        'on-surface': '#e1e2e7',
        'surface-tint': '#00dbe9',
        'primary-container': '#00f0ff',
        'inverse-on-surface': '#2e3134',
        'on-primary-container': '#006970',
        'secondary-fixed': '#f8d8ff',
        primary: '#dbfcff',
        'on-background': '#e1e2e7',
        'primary-fixed-dim': '#00dbe9',
        'on-tertiary-fixed': '#271900',
        'on-error': '#690005',
        'surface-dim': '#111417',
        'secondary-container': '#ce5dff',
        'on-secondary': '#520071',
        'on-secondary-fixed-variant': '#74009f',
        'surface-container-highest': '#323539',
        tertiary: '#fff4e8',
        'on-tertiary-fixed-variant': '#5e4200',
        error: '#ffb4ab',
        'tertiary-fixed-dim': '#ffba20',
        'tertiary-fixed': '#ffdea8',
        'outline-variant': '#3b494b',
        'on-secondary-container': '#480064',
        background: '#111417',
        secondary: '#ebb2ff',
        'on-tertiary': '#412d00',
        'tertiary-container': '#ffd386',
        'surface-variant': '#323539',
        surface: '#111417',
        'on-error-container': '#ffdad6',
        'inverse-primary': '#006970',
        'on-surface-variant': '#b9cacb',
        'on-secondary-fixed': '#320047',
        'surface-container': '#1d2023',
        'on-primary': '#00363a',
        'on-primary-fixed': '#002022',
        'on-primary-fixed-variant': '#004f54',
        'inverse-surface': '#e1e2e7',
        'primary-fixed': '#7df4ff',
        'surface-bright': '#37393d',
        'surface-container-lowest': '#0c0e12',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        'container-max': '1440px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        gutter: '24px',
      },
      fontFamily: {
        'display-lg': ['var(--font-space-grotesk)', 'sans-serif'],
        'data-readout': ['var(--font-jetbrains-mono)', 'monospace'],
        'headline-lg': ['var(--font-space-grotesk)', 'sans-serif'],
        'label-mono': ['var(--font-jetbrains-mono)', 'monospace'],
        'headline-lg-mobile': ['var(--font-space-grotesk)', 'sans-serif'],
        'body-md': ['var(--font-space-grotesk)', 'sans-serif'],
      },
      fontSize: {
        'display-lg': [
          '64px',
          { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'data-readout': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'label-mono': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '500' },
        ],
        'headline-lg-mobile': [
          '28px',
          { lineHeight: '36px', fontWeight: '600' },
        ],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};

export default config;
